#raspberry pi pico in cmake

name: pico-build

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    env:
      PICO_SDK_PATH: $GITHUB_WORKSPACE/pico-sdk
    steps:
    - uses: actions/checkout@v2
    - name: Setup Env
      run: |
        sudo apt install cmake gcc-arm-none-eabi libnewlib-arm-none-eabi
    - name: configure
      run: |
        cmake .
    - name: make
      run: make
